### ISSUE TITLE
HackControl writes one too many bytes.

### ISSUE THREAD

**Issue by UnknownShadow200** [umby24/D3classic#1]
In the function for writing the hack control packet (https://github.com/umby24/D3classic/blob/master/Includes/CPE.pbi#L426), you also write a 'weathercontrol' field.

This field is not included in the final CPE specification, and thus causes clients to crash.

**Comment by umby24** [comment]
Ah indeed it does, my mistake.

On Fri, Sep 11, 2015 at 10:22 PM, UnknownShadow200 <notifications@github.com
